# Generated by Django 4.0 on 2024-04-20 17:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='адрес')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None, verbose_name='телефон')),
                ('experience', models.TextField(blank=True, verbose_name='опыт')),
                ('role', models.CharField(choices=[('perfomer', 'Исполнитель'), ('customer', 'Заказчик')], max_length=30, verbose_name='роль')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
    ]
